sudo: required
services:
  - docker

before_install:
  - docker build -t brainece/react-test -f ./client/Dockerfile.dev ./client 

script:
  - echo "skipping tests"
  #- docker run brainece/react-test npm run test -- --coverage 

after_success:
  - docker build -t brainece/multi-client ./client
  - docker build -t brainece/multi-nginx ./nginx 
  - docker build -t brainece/multi-server ./server 
  - docker build -t brainece/multi-worker ./worker
  # Login in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push brainece/multi-client
  - docker push brainece/multi-nginx 
  - docker push brainece/multi-server 
  - docker push brainece/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'Multidocker- env'
  bucketname: 'elasticbeanstalk-us-east-1-336424150690'
  bucket_path: 'docker-multi'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $$AWS_ACCESS_KEY
    #secure: "$AWS_SECRET_KEY"
  edge: true


 

